<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector"/>
    <PackageReference Include="log4net"/>
    <PackageReference Include="Microsoft.Extensions.Logging.Log4Net.AspNetCore"/>
    <PackageReference Include="Microsoft.NET.Test.Sdk"/>
    <PackageReference Include="Moq"/>
    <PackageReference Include="Moq.AutoMock"/>
    <PackageReference Include="NHamcrest"/>
    <PackageReference Include="NSubstitute"/>
  </ItemGroup>

  <ItemGroup>
    <Using Include="NUnit.Framework"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Agenix.Core\Agenix.Core.csproj"/>
    <ProjectReference Include="..\Agenix.GraphQL\Agenix.GraphQL.csproj"/>
    <ProjectReference Include="..\Agenix.NUnit.Runtime\Agenix.NUnit.Runtime.csproj"/>
    <ProjectReference Include="..\Agenix.Validation.Binary\Agenix.Validation.Binary.csproj"/>
    <ProjectReference Include="..\Agenix.Validation.Json\Agenix.Validation.Json.csproj"/>
    <ProjectReference Include="..\Agenix.Validation.NHamcrest\Agenix.Validation.NHamcrest.csproj"/>
    <ProjectReference Include="..\Agenix.Validation.Text\Agenix.Validation.Text.csproj"/>
    <ProjectReference Include="..\Agenix.Validation.Xml\Agenix.Validation.Xml.csproj"/>
  </ItemGroup>

  <ItemGroup>
    <None Update="log4net.config">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Actions\Dsl\"/>
    <Folder Include="Endpoint\Builder\"/>
    <Folder Include="Interceptor\"/>
    <Folder Include="Server\"/>
  </ItemGroup>

</Project>
