<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <Copyright>Copyright (c) 2025 Agenix</Copyright>
    <Authors>Andrei Suruceanu</Authors>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="log4net" />
    <PackageReference Include="Microsoft.Extensions.Logging.Log4Net.AspNetCore" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="NUnit" />
    <PackageReference Include="NUnit3TestAdapter" />
    <PackageReference Include="System.Formats.Asn1" />
    <PackageReference Include="System.Text.Json" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Agenix.NUnit.Runtime\Agenix.NUnit.Runtime.csproj"/>
    <ProjectReference Include="..\Agenix.Screenplay\Agenix.Screenplay.csproj"/>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Facts\"/>
    <Folder Include="Parallel\"/>
    <Folder Include="Shopping\Questions\"/>
  </ItemGroup>

  <ItemGroup>
    <None Update="log4net.config">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
