#region License

// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements. See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership. The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License. You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied. See the License for the
// specific language governing permissions and limitations
// under the License.
//
// Copyright (c) 2025 Agenix
//
// This file has been modified from its original form.
// Original work Copyright (C) 2006-2025 the original author or authors.

#endregion

namespace Agenix.Screenplay.Consequence;

/// <summary>
///     Represents a logical grouping of consequences that can be evaluated based on a specific question's answer
///     and the provided actor context. This class allows for chaining and evaluation of impacts or results derived
///     from the actor's interaction with a question.
/// </summary>
/// <typeparam name="T">
///     The type of the response generated by the associated question which influences the consequences
///     grouped in this instance.
/// </typeparam>
public class ConsequenceGroup<T> : BaseConsequence<T>
{
    private readonly IQuestion<T> _questionGroup;
    private readonly string _subject;

    /// <summary>
    ///     Represents a group of consequences that can be evaluated within a specific context.
    /// </summary>
    /// <typeparam name="T">The type of the answer that will influence the consequences in the group.</typeparam>
    public ConsequenceGroup(IQuestion<T> questionGroup)
    {
        _questionGroup = questionGroup;
        _subject = QuestionSubject<T>.FromClass(questionGroup.GetType()).AndQuestion(questionGroup).Subject();
    }

    /// <summary>
    ///     Evaluates the consequences under the context of the specified actor
    ///     by performing associated setup actions and responding to the provided question.
    /// </summary>
    /// <param name="actor">The actor who will evaluate and answer the question involved in this consequence group.</param>
    public override void EvaluateFor(Actor actor)
    {
        PerformSetupActionsAs(actor);
        _questionGroup.AnsweredBy(actor);
    }

    /// <summary>
    ///     Converts the current instance of the <see cref="ConsequenceGroup{T}" /> to its string representation.
    /// </summary>
    /// <returns>
    ///     A string that represents the current <see cref="ConsequenceGroup{T}" />, formatted using the explanation
    ///     template and subject text.
    /// </returns>
    public override string ToString()
    {
        var template = Explanation.OrElse("Then {0}");
        return AddRecordedInputValuesTo(string.Format(template, SubjectText.OrElse(_subject)));
    }
}
