<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector"/>
    <PackageReference Include="log4net"/>
    <PackageReference Include="Microsoft.Extensions.Logging.Log4Net.AspNetCore"/>
    <PackageReference Include="Microsoft.NET.Test.Sdk"/>
    <PackageReference Include="Moq"/>
  </ItemGroup>

  <ItemGroup>
    <Using Include="NUnit.Framework"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Agenix.NUnit.Runtime\Agenix.NUnit.Runtime.csproj"/>
    <ProjectReference Include="..\Agenix.Playwright\Agenix.Playwright.csproj"/>
  </ItemGroup>

  <ItemGroup>
    <None Update="log4net.config">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Actions\"/>
    <Folder Include="Config\Attribute\"/>
  </ItemGroup>

  <ItemGroup>
    <None Remove="agenix-application.json"/>
    <Content Include="agenix-application.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
