<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Playwright" Version="1.53.0"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Agenix.Core\Agenix.Core.csproj"/>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Actions\Dsl\"/>
    <Folder Include="Config\"/>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Extension\agenix\endpoint\builder\playwright"/>
    <EmbeddedResource Include="Extension\agenix\endpoint\component\playwright"/>
    <EmbeddedResource Include="Extension\agenix\endpoint\parser\playwright"/>
  </ItemGroup>

</Project>
