name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3 # Updated to the latest version of setup-dotnet action
        with:
          dotnet-version: 8.0.x # Updated to .NET 8

      - name: Restore dependencies
        run: dotnet restore
      
      - name: Build
        run: dotnet build --no-restore
      
      - name: Test
        run: dotnet test --no-build --verbosity normal --logger "nunit;LogFileName=test-results.xml" || true
        
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: NUnit Tests
          path: "**/test-results.xml"
          reporter: nunit
          fail-on-error: true
